export const studentColumnAccessors = {
	index: 'STT',
	name: 'Họ tên',
	mssv: 'MSSV',
	email: 'Email',
	phoneNumber: 'Số điện thoại',
	course: 'Khóa nhập học',
	majorCode: 'Mã ngành',
	support: 'Hình thức',
	statusCheck: 'Trạng thái thực tập',
	statusStudent: 'Trạng thái sinh viên',
	nameCompany: 'Công ty thực tập',
	addressCompany: 'Địa chỉ công ty',
	taxCode: 'Mã số thuế',
	dream: 'Vị trí thực tập',
	position: 'Vị trí người tiếp nhận',
	CV: 'CV',
	report: 'Báo cáo TT',
	form: 'Biên bản TT',
	resultScore: 'Điểm kết quả',
	attitudePoint: 'Điểm thái độ',
	reviewer: 'Reviewer',
	createdAt: 'Ngày bổ sung',
	note: 'Ghi chú'
};
