export const columnAccessors = {
	index: "STT",
	name: "Họ tên",
	course: "Khóa nhập học",
	statusCheck: "Trạng thái thực tập",
	statusStudent: "Trạng thái sinh viên",
	email: "Email",
	mssv: "MSSV",
	support: "Hình thức",
	phoneNumber: "Số điện thoại",
	CV: "CV",
	nameCompany: "Công ty thực tập",
	additionalDate: "Ngày bổ sung",
	reviewer: "Reviewer",
	majorCode: "Mã ngành",
	addedAt: "Ngày bổ sung",
	position: "Vị trí thực tập",
	note: "Ghi chú",
};
